### ISSUE TITLE
How to specify CS pin

### ISSUE THREAD

**Issue by got879** [SunitRaut/WSN-for-RFM69-LowPowerLab#12]
How to create the object and include specifying the CS and INT pins? If this is possible please provide an example.

Thanks.

**Comment by SunitRaut** [comment]
Hi got879,

To define CS and INT pins for RFM69 library, you can declare your object as below:

`WSN_RFM69 node(CS_pin, INT_pin);`

Here, CS_pin and INT_pin are your CS and INT pins respectively. 

A small note for future reference: 
The hardware interface is exactly the same as for LowPowerLab RFM69 library. We have only added Wireless Networking capability on top of LowPowerLab RFM69 library. So in case of any doubts you can lookup this library for help regarding hardware/radio related issues ([https://github.com/LowPowerLab/RFM69](https://github.com/LowPowerLab/RFM69)).

Have a great time building your project!
